[package]
name = "jsonnet-tf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "^1.0"

[dependencies.uuid]
version = "^1.17.0"
# Lets you generate random UUIDs
features = [
    "v4",
]
